branches:
only:
  - master
language: python
notifications:
email:
on_success: change
on_failure: always
irc: chat.freenode.net#dedupe
python:
  - '2.7'
install:
  - pip install -r requirements.txt
after_success: coveralls
sudo: false
addons:
  postgresql: "9.3"
install: "pip install -r requirements.txt"
before_script:
  - cp tests/test_config.py.travis tests/test_config.py
  - psql -c 'create database dedupe_test;' -U postgres
script: coverage run -m nose
